### Segundo intento de implementación

In [1]:
using PyCall
using LaTeXStrings
@pyimport numpy as np
using SymPy
using Roots
using Plots
#using Plots

┌ Warning: `@pyimport foo` is deprecated in favor of `foo = pyimport("foo")`.
│   caller = _pywrap_pyimport(::PyObject) at PyCall.jl:410
└ @ PyCall /home/eve/.julia/packages/PyCall/BcTLp/src/PyCall.jl:410


In [3]:
composition(f, n) = ∘(ntuple(_ -> f, n)...) # donde f es una funcion de una variable y composition regresa una funcion

composition (generic function with 1 method)

In [4]:
CompositionMap(M,n) = [composition(M[1],n), composition(M[2],n)]

CompositionMap (generic function with 1 method)

In [19]:
function EstandardMap(r)
    x = r[1]
    y = r[2]
    vx = x + y - 0.3*sin(2*pi*x)/2*pi
    vy =  y - 0.3*sin(2*pi*x )/2*pi 
    return [vx,vy]
end
    

EstandardMap (generic function with 3 methods)

 🔴 componer la funcion 

In [20]:
compo1(r)=composition(EstandardMap,2)(r)

compo1 (generic function with 3 methods)

Para revisar que la composicion funciona

In [16]:
x = Sym("x")
y = Sym("y")
κ = Sym("κ")

κ

In [24]:
compo1([x,y])

2-element Array{Sym,1}:
 x + 2*y - 0.3*pi*sin(6.28318530717959*x) - 0.15*pi*sin(6.28318530717959*x + 6.28318530717959*y - 0.942477796076938*pi*sin(6.28318530717959*x))
      y - 0.15*pi*sin(6.28318530717959*x) - 0.15*pi*sin(6.28318530717959*x + 6.28318530717959*y - 0.942477796076938*pi*sin(6.28318530717959*x))

In [26]:
compo1([x,y])[1]

x + 2⋅y - 0.3⋅π⋅sin(6.28318530717959⋅x) - 0.15⋅π⋅sin(6.28318530717959⋅x + 6.28
318530717959⋅y - 0.942477796076938⋅π⋅sin(6.28318530717959⋅x))

🔴 Ahora aplicamos la composicion a un punto en una de los conjuntos de la simetria, en este caso el $I_{0}$

In [28]:
compo1([0,y])

2-element Array{Sym,1}:
 2*y - 0.15*pi*sin(6.28318530717959*y)
   y - 0.15*pi*sin(6.28318530717959*y)

In [29]:
mapeo1(y) = compo1([0,y])

mapeo1 (generic function with 1 method)

🔴 uso las funciones anteriores para buscar que esten en la simetria $I_{1}$

In [30]:
F(y) = compo1([0,y])[1]-(compo1([0,y])[2]+1)/2

F (generic function with 1 method)

In [31]:
using Roots

In [37]:
find_zero(F,0.8)

0.41407652795392963

In [45]:
F1(y) = (compo1([0,y])[1]-(compo1([0,y])[2])/2)

F1 (generic function with 1 method)

In [46]:
find_zero(F1,0.4)

0.0

🔴 Ahora si empezamos en la otra simetria 

In [47]:
compo1([1/2,y])

2-element Array{Sym,1}:
 2*y - 0.15*pi*sin(6.28318530717959*y - 1.15420241623307e-16*pi + 3.14159265358979) - 3.67394039744206e-17*pi + 0.5
         y - 0.15*pi*sin(6.28318530717959*y - 1.15420241623307e-16*pi + 3.14159265358979) - 1.83697019872103e-17*pi

In [48]:
F(y) = compo1([1/2,y])[1]-(compo1([1/2,y])[2]+1)/2

F (generic function with 1 method)

In [49]:
find_zero(F,0.5)

1.491448663511446e-16

In [57]:
find_zeros(F,-0.011,1)

1-element Array{Float64,1}:
 1.657435237675999e-16

In [58]:
F1(y) = compo1([1/2,y])[1]-(compo1([1/2,y])[2])/2

F1 (generic function with 1 method)

In [59]:
find_zeros(F1,-0.01,1.0)

0-element Array{Float64,1}

In [63]:
mod(find_zero(F1,0.8),1)

0.8119836006596095

🔴 Ahora con la otra simetria 

In [81]:
F(y) = compo1([y/2,y])[1]

F (generic function with 1 method)

In [82]:
find_zero(F,0.6)

0.5361682361342845

In [83]:

find_zero(F,0.4)

0.0

In [72]:
find_zero(F,0.8)

0.5361682361342845

In [76]:
F1(y) = compo1([y/2,y])[1]-1/2

F1 (generic function with 1 method)

In [80]:
find_zero(F1,0.8)

0.6040767035908375

🔴 Ahora con la ultima simetria

In [84]:
F(y) = compo1([(y+1)/2,y])[1]

F (generic function with 1 method)

In [86]:
find_zero(F,0.7)

-0.03679268821145595

In [87]:
F1(y) = compo1([(y+1)/2,y])[1]-1/2

F1 (generic function with 1 method)

In [90]:
find_zero(F1,0.7)

1.1102230246251565e-16

⭐ Vamos a ver si podemos hacer funciones para implementarlo 

In [92]:
composition(f, n) = ∘(ntuple(_ -> f, n)...) # donde f es una funcion de una variable y composition regresa una funcion

composition (generic function with 1 method)

In [93]:
CompositionMap(M,n) = [composition(M[1],n), composition(M[2],n)]

CompositionMap (generic function with 1 method)

In [153]:
simetria1(x,y) = [0,y]
# simetria2([x,y]) = [1/2,y]
 simetria3(x,y) = [y/2,y]
# simetria4([x,y]) = [(y+1)/2,y]

simetria3 (generic function with 1 method)

In [102]:
mapeo5(v) = composition(EstandardMap,3)(v)

mapeo5 (generic function with 2 methods)

In [143]:
m = mapeo5([simetria1(x,y)[1],simetria1(x,y)[2]])

2-element Array{Sym,1}:
 3*y - 0.3*pi*sin(6.28318530717959*y) - 0.15*pi*sin(12.5663706143592*y - 0.942477796076938*pi*sin(6.28318530717959*y))
  y - 0.15*pi*sin(6.28318530717959*y) - 0.15*pi*sin(12.5663706143592*y - 0.942477796076938*pi*sin(6.28318530717959*y))

In [111]:
simetria3(x,y)

2-element Array{Sym,1}:
 y/2
   y

In [120]:
simetria3(x,m[2])[1]

y                                                                             
─ - 0.075⋅π⋅sin(6.28318530717959⋅y) - 0.075⋅π⋅sin(12.5663706143592⋅y - 0.94247
2                                                                             

                                     
7796076938⋅π⋅sin(6.28318530717959⋅y))
                                     

In [121]:
t(y) = m[1] - simetria3(x,m[2])[1]

t (generic function with 1 method)

In [123]:
find_zero(m[1] - simetria3(x,m[2])[1],0.4)

0.33605222896938125

In [125]:
find_zero(t(y),0.4)

0.33605222896938125

In [161]:
function puntoperiodicoy(mapeo,n, simetria1, simetria2 ,semilla)
    mapeoc(v) = composition(mapeo,n)(v)
    m = mapeoc([simetria1(x,y)[1], simetria1(x,y)[2]])
    t(y) = m[1]- simetria2(x,m[2])[1]
    cero_y = find_zero(t(y),semilla)
    return cero_y
end

puntoperiodicoy (generic function with 1 method)

In [167]:
function puntoperiodicox(puntoy,simetria1)
    x = simetria1(0,puntoy)[1]
    puntop = [x,puntoy]
    return puntop
end

puntoperiodicox (generic function with 1 method)

In [162]:
puntoperiodicoy(EstandardMap,5,simetria1,simetria3,0.4)

0.38718353513147424

In [168]:
puntoperiodicox(0.38718353513147424,simetria1)

2-element Array{Float64,1}:
 0.0
 0.38718353513147424

In [ ]:
puntoperiodicoy(EstandardMap,5,simetria2,simetria3,0.6)