# El mapeo non-twist y sus orbitas periodicas

In [1]:
using PyPlot
using TaylorSeries
using IntervalArithmetic, IntervalRootFinding
using ValidatedNumerics
using StaticArrays
using PyCall
using LaTeXStrings
#@pyimport matplotlib.patches as patch
@pyimport numpy as np
#@pyimport matplotlib.pyplot as plt

┌ Warning: `@pyimport foo` is deprecated in favor of `foo = pyimport("foo")`.
│   caller = _pywrap_pyimport(::PyObject) at PyCall.jl:399
└ @ PyCall /home/eve/.julia/packages/PyCall/zqDXB/src/PyCall.jl:399


In [2]:
push!(LOAD_PATH,"/home/eve/Documents/Tesis-v-1.0.2/Programas/IPM")

4-element Array{String,1}:
 "@"
 "@v#.#"
 "@stdlib"
 "/home/eve/Documents/Tesis-v-1.0.2/Programas/IPM"

In [3]:
using ParametrizacionMetodo
using mapeos

In [4]:
using SymPy

In [7]:
x = Sym("x")
y = Sym("y")
a = Sym("a")
b = Sym("b")

b

In [8]:
#defino las ecuaciones para el mapeo pero ahora simbolicas.
NT(x,y,a,b) = [x+a*(1-(y-b*sin(2*pi*x))^2), y-b*sin(2*pi*x)]

NT (generic function with 1 method)

In [9]:
NT1 = NT(x,y,a,b)

2-element Array{Sym,1}:
 a*(1 - (-b*sin(6.28318530717959*x) + y)^2) + x
                 -b*sin(6.28318530717959*x) + y

In [10]:
NT1[2]

-b⋅sin(6.28318530717959⋅x) + y

In [11]:
NT2 =NT(NT1[1],NT1[2],a,b)

2-element Array{Sym,1}:
 a*(1 - (-b*sin(6.28318530717959*x) + y)^2) + a*(1 - (-b*sin(6.28318530717959*x) - b*sin(6.28318530717959*a*(1 - (-b*sin(6.28318530717959*x) + y)^2) + 6.28318530717959*x) + y)^2) + x
                                                              -b*sin(6.28318530717959*x) - b*sin(6.28318530717959*a*(1 - (-b*sin(6.28318530717959*x) + y)^2) + 6.28318530717959*x) + y

In [12]:
NonT2 = NT2-[x,y]

2-element Array{Sym,1}:
 a*(1 - (-b*sin(6.28318530717959*x) + y)^2) + a*(1 - (-b*sin(6.28318530717959*x) - b*sin(6.28318530717959*a*(1 - (-b*sin(6.28318530717959*x) + y)^2) + 6.28318530717959*x) + y)^2)
                                                              -b*sin(6.28318530717959*x) - b*sin(6.28318530717959*a*(1 - (-b*sin(6.28318530717959*x) + y)^2) + 6.28318530717959*x)

In [13]:
@vars x y
eq_a = subs(NonT2[1],b,0.7425)
eq_b = subs(NonT2[2],b,0.7425)



                                            ⎛                   ⎛             
-0.7425⋅sin(6.28318530717959⋅x) - 0.7425⋅sin⎝6.28318530717959⋅a⋅⎝1 - (y - 0.74

                           2⎞                     ⎞
25⋅sin(6.28318530717959⋅x)) ⎠ + 6.28318530717959⋅x⎠

In [ ]:
eq1 = subs(eq_a, a, 0.001)
eq2 = subs(eq_b,a,0.001)
solve([eq1, eq2], [x,y])

Vamos a ver si son de periodo 2 o de periodo 1

In [23]:
b = 0.7425
a = 0.0
NT(0.5,6.0,a,b)

2-element Array{Float64,1}:
 0.5
 6.0

In [14]:
Est3 = Est(Est2[1],Est2[2],k)

2-element Array{Sym,1}:
           k*sin(y) + k*sin(k*sin(y) + x + y) + k*sin(2*k*sin(y) + k*sin(k*sin(y) + x + y) + 2*x + y) + x
 3*k*sin(y) + 2*k*sin(k*sin(y) + x + y) + k*sin(2*k*sin(y) + k*sin(k*sin(y) + x + y) + 2*x + y) + 3*x + y

In [15]:
Estandar3 = Est3-[x,y]

2-element Array{Sym,1}:
           k*sin(y) + k*sin(k*sin(y) + x + y) + k*sin(2*k*sin(y) + k*sin(k*sin(y) + x + y) + 2*x + y)
 3*k*sin(y) + 2*k*sin(k*sin(y) + x + y) + k*sin(2*k*sin(y) + k*sin(k*sin(y) + x + y) + 2*x + y) + 3*x

In [ ]:
\:star: Buscamos puntos de periodo 3 en el mapeo estandar

In [ ]:
@vars x y
eq1 = subs(Estandar3[1],k,0.1)
eq2 = subs(Estandar3[2],k,0.1)
solve([eq1, eq2], [x,y])